name: run-digger
description: Manage terraform collaboration
author: Digger

outputs:
  output:
    value: ${{ steps.digger.outputs.output }}
    description: The terraform output

runs:
  using: composite
  steps:
    - uses: actions/download-artifact@v3
      with:
          name: plans
          path: '*.tfplan'
    - name: print plan files
      shell: bash
      run: |
          ls -la *.tfplan
    - name: build and run digger
      if: ${{ !startsWith(github.action_ref, 'v') }}
      shell: bash
      run: |
          cd ${{ github.action_path }}
          go build -o digger ./cmd/digger
          chmod +x digger
          mv digger /usr/local/bin/digger
          cd ${{ github.workspace }}
          digger
    - name: run digger
      if: ${{ startsWith(github.action_ref, 'v') }}
      env:
        actionref: ${{ github.action_ref }}
      id: digger
      shell: bash
      run: |
        curl -sL https://github.com/diggerhq/digger/releases/download/${actionref}/digger-${{ runner.os  }}-${{ runner.arch }} -o digger
        chmod +x digger
        mv digger /usr/local/bin/digger
        cd ${{ github.workspace }}
        digger
    - name: upload plan
      uses: actions/upload-artifact@v3
      with:
          name: plans
          path: '*.tfplan'
          retention-days: 14

branding:
  icon: globe
  color: purple
